export { default as ErrorPage } from './ErrorPage';
export { default as HomePage } from './HomePage';
export { default as ProtectedRoute } from './ProtectedRoute';
export { default as RegisterPage } from './RegisterPage';
export { default as UserProfilePage } from './UserProfilePage';
export { default as AllBoardsPage } from './boards/AllBoardsPage';
export { default as EditBoardPage } from './boards/EditBoardPage';
export { default as EditTaskPage } from './tasks/EditTaskPage';
export { default as TaskPage } from './tasks/TaskPage';
